version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
